version:  '3.7'

services:
    vehiclesapi:
        build: ./VehiclesAPI
        command: python3 ./manage.py runserver 0.0.0.0:8080
        ports:
            - 8080:8080
        volumes:
            - ./VehiclesAPI/:/usr/app


